version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # AWS
  AWS_ACCESS_KEY_ID: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
  AWS_SECRET_ACCESS_KEY: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  AWS_SESSION_TOKEN: session_token (Used to generate Redshift credentials)
  AWS_REGION: "us-east-1"
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: "{{ env_var('POSTGRES_DBNAME') }}"
  POSTGRES_SCHEMA: "{{ env_var('POSTGRES_SCHEMA') }}"
  POSTGRES_USER: "{{ env_var('POSTGRES_USER') }}"
  POSTGRES_PASSWORD: "{{ env_var('POSTGRES_PASSWORD') }}"
  POSTGRES_HOST: "{{ env_var('POSTGRES_HOST') }}"
  POSTGRES_PORT: "{{ env_var('POSTGRES_PORT') }}"
  # Redshift
  # REDSHIFT_SCHEMA: public # Optional
  # REDSHIFT_DBNAME: redshift_db_name
  # REDSHIFT_HOST: redshift_cluster_id.identifier.region.redshift.amazonaws.com
  # REDSHIFT_PORT: 5439
  # REDSHIFT_TEMP_CRED_USER: temp_username
  # REDSHIFT_TEMP_CRED_PASSWORD: temp_password
  # REDSHIFT_DBUSER: redshift_db_user
  # REDSHIFT_CLUSTER_ID: redshift_cluster_id
  # REDSHIFT_IAM_PROFILE: default
  # DuckDB
  # DUCKDB_DATABASE: database
  # DUCKDB_SCHEMA: main
  # Google
  # GOOGLE_SERVICE_ACC_KEY:
  #   type: service_account
  #   project_id: project-id
  #   private_key_id: key-id
  #   private_key: "-----BEGIN PRIVATE KEY-----\nyour_private_key\n-----END_PRIVATE_KEY"
  #   client_email: your_service_account_email
  #   auth_uri: "https://accounts.google.com/o/oauth2/auth"
  #   token_uri: "https://accounts.google.com/o/oauth2/token"
  #   auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
  #   client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/your_service_account_email"
  # GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/path/to/your/service/account/key.json"
  # GOOGLE_LOCATION: US # Optional
